### ISSUE TITLE
Test cache behavior on dashboard upgrade

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard-plugins#6087]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.6.0 | 0 | Chrome, Firefox, Safari |

**Description**

Update a 4.5.x deployment to 4.6.0 following the upgrade guide. Test whether the browser cache should be cleared or not. Add evidence of the test, in the form of videos and screenshots of the cache test, in the issue comments.

If there is no need to clear the cache, open an issue and create a PR to the documentation repo, to remove the clear cache step from the upgrade guide.

**Comment by Tostti** [comment]
# Test

### Installed an environment with version `4.5.3` and navigate through several places

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/a23eafb0-190c-4faf-a68a-73bb9ba97175)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/a83cc862-bf6e-48a5-8b78-197c53a09b07)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/ecd8c917-6435-44b2-84a7-b469c6e75a43)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/27a18bc2-3101-47d4-b7b5-ae99af50aeba)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/b23573b3-0ba5-4749-a69d-295b57c53318)

### Upgraded to 4.6.0

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/faca5f96-2451-4d1f-a0b6-80efbee3f84a)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/0650318a-fcae-4ba2-8cac-43fa3c8a77b8)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/4422f843-f5fa-4012-968e-970998a6339a)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/6ddf1aac-b6f2-4da8-9713-6fbd49279887)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/c277dc8d-e55a-4780-b07e-3bf30a16275b)

## Verify a specific case on which a css is changed to see if cache affects it

On the groups section, the name of the agent is black and almost not visible in dark mode. This is fixed in 4.7.0, although it is not released yet, I upgraded my environment with the development packages only for this test.

### 4.6.0

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/043dd93f-2ed0-4308-87a1-1ffc051becfc)


### 4.7.0

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/61c916bb-2e32-4490-ab33-c78d54605740)


It's confirmed that even without clearing the cache, the changes are correctly applied.

**Comment by Tostti** [comment]
PR successfully merged
