### ISSUE TITLE
Vulnerabilities module/Inventory tab, the refresh button does not update the information.

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-dashboard-plugins#6329]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 02 | Chrome, Firefox, Safari, etc |

**Description**
In the Inventory tab from the Vulnerabilities module, the refresh button does not update the information.

**Preconditions**
1. 

**Steps to reproduce**
1. Navigate to 'Vulnerabilities/Inventory'
2. Click on 'refresh button'
3. See if he makes any requests

(you can add a new agent to have more vulnerabilities and see that it does not update the data until you change tabs.)

**Expected Result**
1. the data in the table is updated

**Actual Result**
1. 

https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/0b98d010-9212-4473-a001-75992213f506

**Comment by asteriscos** [comment]
I tested this behavior en the Discover native plugin to check if this was an OpenSearch issue and it turns out it is. There's an issue reported for 2.10 and should be fixed by 2.11:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5314

I will close this issue as it will be fixed by OpenSearch.
