### ISSUE TITLE
Statistics error when cluster mode is disabled

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6343]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 02 | Chrome, Firefox, Safari, etc |

**Description**
The Statistics view throws an error whenever the cluster mode is disabled. Seems to be making requests to cluster endpoints although it shouldn't in case the cluster mode is disabled.

https://github.com/wazuh/wazuh-dashboard-plugins/blob/v4.8.0-2.10.0-alpha2/plugins/main/public/controllers/management/components/management/statistics/statistics-overview.js#L85-L91

**Preconditions**
1. Cluster mode should be disabled in Wazuh Manager

**Steps to reproduce**
1. Navigate to Statistics
2. See the error

**Expected Result**
1. If the cluster mode is disabled it shouldn't try to get statistics from the cluster

**Actual Result**
1. The view is making cluster endpoint requests

**Screenshots**

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/52d51b7f-0ab6-41f9-aa53-07b6445dfc99)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/9d11f29c-6970-4ce4-8a84-68da7f1965f2)

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/58492e76-0723-4bdd-8d57-86e79fc278bd)

**Comment by lucianogorza** [comment]
# Analysis
In the first place, the error is produced because the code tries to get the cluster nodes without asking first if the server is in cluster mode or manager mode.
In the file `plugins/main/public/controllers/management/components/management/statistics
/statistics-overview.js` it is this code:
```js
const data = await clusterNodes();
```
First, we have to ask if the server is in cluster mode or not. For example:
```js
const clusterStatus = await clusterReq();
const isClusterMode =
  clusterStatus.data.data.enabled === 'yes' &&
  clusterStatus.data.data.running === 'yes';
if (isClusterMode) {
 ...
} else {
 ....
}
```

**Comment by lucianogorza** [comment]
### Visualization: Total number of bytes received with Imposter

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/350f6353-b24a-4c9d-b4ea-f09900ba84c1)

#### Visualization definition

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/5080306c-58cf-496e-9057-292a9673b88b)

```json
{
    "attributes": {
        "title": "Wazuh App Statistics remoted Recv bytes",
        "visState": "{\"title\":\"Wazuh App Statistics remoted Recv bytes\",\"type\":\"line\",\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"avg\",\"params\":{\"field\":\"remoted.recv_bytes\",\"customLabel\":\"Count\"},\"schema\":\"metric\"},{\"id\":\"2\",\"enabled\":true,\"type\":\"date_histogram\",\"params\":{\"field\":\"timestamp\",\"timeRange\":{\"from\":\"now-24h\",\"to\":\"now\"},\"useNormalizedOpenSearchInterval\":true,\"scaleMetricValues\":false,\"interval\":\"auto\",\"drop_partials\":false,\"min_doc_count\":1,\"extended_bounds\":{},\"customLabel\":\"timestamp\"},\"schema\":\"segment\"},{\"id\":\"3\",\"enabled\":true,\"type\":\"filters\",\"params\":{\"filters\":[{\"input\":{\"query\":\"remoted.recv_bytes:*\",\"language\":\"kuery\"},\"label\":\"recv_bytes\"}]},\"schema\":\"group\"}],\"params\":{\"type\":\"line\",\"grid\":{\"categoryLines\":true},\"categoryAxes\":[{\"id\":\"CategoryAxis-1\",\"type\":\"category\",\"position\":\"bottom\",\"show\":true,\"style\":{},\"scale\":{\"type\":\"linear\"},\"labels\":{\"show\":true,\"filter\":true,\"truncate\":100},\"title\":{}}],\"valueAxes\":[{\"id\":\"ValueAxis-1\",\"name\":\"LeftAxis-1\",\"type\":\"value\",\"position\":\"left\",\"show\":true,\"style\":{},\"scale\":{\"type\":\"linear\",\"mode\":\"normal\"},\"labels\":{\"show\":true,\"rotate\":0,\"filter\":false,\"truncate\":100},\"title\":{\"text\":\"Count\"}}],\"seriesParams\":[{\"show\":true,\"type\":\"line\",\"mode\":\"normal\",\"data\":{\"label\":\"Count\",\"id\":\"1\"},\"valueAxis\":\"ValueAxis-1\",\"drawLinesBetweenPoints\":true,\"lineWidth\":2,\"interpolate\":\"linear\",\"showCircles\":true}],\"addTooltip\":true,\"addLegend\":true,\"legendPosition\":\"right\",\"times\":[],\"addTimeMarker\":false,\"labels\":{},\"thresholdLine\":{\"show\":false,\"value\":10,\"width\":1,\"style\":\"full\",\"color\":\"#E7664C\"}}}",
        "uiStateJSON": "{\"vis\":{\"colors\":{\"recv_bytes\":\"#70DBED\"}}}",
        "description": "",
        "version": 1,
        "kibanaSavedObjectMeta": {
            "searchSourceJSON": "{\"index\":\"wazuh-statistics-*\",\"filter\":[{\"match_phrase\":{\"apiName\":\"imposter\"}}],\"query\":{\"query\":\"\",\"language\":\"lucene\"}}"
        }
    },
    "type": "visualization",
    "id": "Wazuh-App-Statistics-remoted-Recv-bytes",
    "_version": 1
}
```

## Refresh button bug

Testing the functionality we found that the `Refresh` button only gets the charts definitions and doesn't request the data.

![Refresh button](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/19257e67-4af8-4f80-9c50-0f27974a7fd4)

**Comment by lucianogorza** [comment]
# Refresh button bug

Testing the functionality we found that the `Refresh` button only gets the visualization definitions and doesn't request the data.

![Refresh button](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/19257e67-4af8-4f80-9c50-0f27974a7fd4)

**Comment by lucianogorza** [comment]
# Conclusions
- **Adding the code to manage if the server is in cluster mode fixes the initial error** and data is retrieved for both options.
- When the server is in **cluster mode off**, **two visualizations make no sense** because they have an aggregation by node: `Events processed` and `Events Dropped`.
- There is a **bug** when selecting a node: The visualizations don't apply the filter.
- There is a **bug** when pressing the `Refresh` button: only get the definitions.

**Comment by lucianogorza** [comment]
# Server management -> Cluster 
We should check if the definitions of visualizations are using the correct index pattern in the file: 

`plugins/wazuh/server/integration-files/visualizations/cluster/monitoring.ts`

And we should check the filter applied in the file:

`plugins/wazuh/server/controllers/wazuh-elastic.ts`

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/103193307/8808985c-61e9-49e1-911a-174565051a7b)

According the data analysis the fields `cluster.name` and `cluster.node` are not present in the index patter `wazuh-alerts`

**Comment by lucianogorza** [comment]
# Conclusions and solutions

## Initial error when cluster mode is disabled 🟢 
**Adding the code to manage if the server is in cluster mode fixes the initial error** and data is retrieved for both options. https://github.com/wazuh/wazuh-dashboard-plugins/issues/6343#issuecomment-1898809750

## 
- When the server is in **cluster mode off**, **two visualizations make no sense** because they have an aggregation by node: `Events processed` and `Events Dropped`. Maybe it's convenient to define the visualizations without the aggregation by node when cluster mode is off.
  - We decided to replace the definitions of visualizations `Events processed` and `Events Dropped` according to the cluster mode.
- There is a **bug** when selecting a node: The visualizations don't apply the filter.
  - We decided to fix the bug managing the filter by node in the backend.
- There is a **bug** when pressing the `Refresh` button: only get the definitions.
  - By the moment we decided to fix in a future release.

**Comment by lucianogorza** [comment]
# Conclusions and solutions

## [Initial error when cluster mode is disabled](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6343#issuecomment-1898809750) 🟢 

- **Adding the code to manage if the server is in cluster mode fixes the initial error** and data is retrieved for both options.

## [Visualizations without data when cluster mode is disabled](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6343#issuecomment-1899085528) 🟢 

- When **cluster mode is disabled**, **two visualizations make no sense** because they have an aggregation by node: `Events processed` and `Events Dropped`.
- We decided to replace the definitions of visualizations `Events processed` and `Events Dropped` according to the cluster mode.

## Visualizations don't apply the filter by node 🟢 

- There is a **bug** when selecting a node: The visualizations don't apply the filter.
- We decided to fix the bug by managing the filter by node in the backend.

## [Refresh button bug](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6343#issuecomment-1899107305) 🟡 
- By the moment we decided to fix in a future release.

## Server management -> Cluster 🟡 

- Check definitions of visualizations and applied filters.
