### ISSUE TITLE
Add validations in the Vulnerabilities dashboard and inventory views 

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6394]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 03 | Chrome, Firefox, Safari, etc |

**Description**

The Vulnerabilities module depends on the existence of the vulnerabilities index-pattern and its corresponding indexes to work. Therefore we must ensure these conditions are met before attempting to load the visualizations.

We need to wrap the vulnerabilities views with a high-order component that checks these prerequisites.

### Validations

1. Vulnerabilities index-pattern must exist. Otherwise, if indexes exist, try to create it.
2. In case the index-pattern doesn't exist and cannot be created, render a callout with a message suggesting to check Wazuh server configuration
3. On the other hand, make a request to determine if a Wazuh worker node from the cluster has the vulnerabilities module configured. In case it's disabled inform the user about it.

![vulnerabilities-HOC](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/c4ab6719-1730-4c78-b63c-a364d90e52b1)

#### Dashboard

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/32bd42c2-9411-4387-a910-15e3e1e30421)

#### Inventory

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/3f512c52-3aee-4351-a1f3-121ac0df9a5c)

**Comment by Desvelao** [comment]
# Research

I was working on a solution using an HOC that wraps the Dashboard and Inventory tabs with logic to check the existence of the index pattern.

This solution causes when navigating to `Events` tab, the related filters are not added. We saw the filters were defined when the Dashboard or Inventory tabs components are unmounted, so it is needed the logic of the `useSearchBarConfiguration` must be execute to set the expected filters to work in `Events` tab.

I moved the logic from the HOC to the inner of the `Dashboard` and `Inventory` components allowing the definition of the filters to be done through the `useSearchBarConfiguration`. This solved the problem the `Events` tab didn't have the expected implicit filters.

**Comment by Desvelao** [comment]
# Problem

We found another problem when navigating to the `Events` tab of the `Vulnerabilities Detection`, the filter releated to `cluster.name` was disabled. This happens when there is not the `wazuh-states-vulnerabilities` index.

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/34042064/8425c07c-4120-431f-80b0-dab58d4dcd28)

# Digging

I was researching this problem and I found the `filter.meta.disable` property is changed from `false` to `true` by a component from the platform `FilterItem` (`FilterBarUI`).

This happens when redefining the filters to navigate from `Dashboard`/`Inventory` to `Events` tab.

In the render of a FilterItem, using the filter related the `wazuh.cluster.name` causes the `filter.meta.disable` to `false` and set the `indexPatternExists` as false. Then, the filter is redefined as `cluster.name` but the internal state of the component is the same.

Forcing the component to be unmounted could solve the problem.

I found the login related `FilterItem` component of the search bar was executed despite the search bar is not displayed, so it seems there is a hidden search bar that is causing the changes the property to disable the filter.

**Comment by Desvelao** [comment]
We could find a solution to this problem https://github.com/wazuh/wazuh-dashboard-plugins/issues/6394#issuecomment-1941898757 delaying the set of related filters.

This delay causes another problem when navigating from `Dashboard` to `Inventory` or vice versa.

We decided to solve these problems at the moment, protecting the `Dashboard`, `Inventory`, and `Events` tabs with a check of the existence of the `wazuh-states-vulnerabilities` index pattern. If it doesn't exist and cannot be created it due to there being no indices matching, then the access to the related view is retricted. The Dashboard and Inventory view sets the filters for the `Events` tab too.

The `Events` tab could be not accessed if there is no the index pattern related to the `wazuh-vulnerabilities-states` despite the data displayed on this view is related to `wazuh-alerts-*`.

We will need to work on better management of the filters in the search bar in future iterations.

**Comment by Desvelao** [comment]
@lucianogorza found a problem https://github.com/wazuh/wazuh-dashboard-plugins/pull/6405#issuecomment-1944460158, that is related to the current flow to set the filters is not running for that particular case.

To fix it, we decided to redirect to the `Dashboard` tab, that if the index pattern was created, the component should be visible, and if the user navigates to the `Events` tab, the logic to define the filters related to the `Events` tab should be applied following the current flow (not changed on the pull request) to set the filters when the `Dashboard` or `Inventory` tabs are unmounted.
