### ISSUE TITLE
Filter settings not preserved when switching from Dashboard/Inventory to Event menu in Vulnerability Detection section

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-dashboard-plugins#6415]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0| beta1 | Firefox |

**Description**
The filter settings are not retained when transitioning from the Dashboard/Inventory to the Event view within the Vulnerability Detection section.

**Preconditions**
1. Deploy an All-In-One

**Steps to reproduce**
1. Navigate to Vulnerability Detection section
2. Go to the dashboard view
3. Create a filter. For example to show only manager alerts (agent.id: 000)
4. Go to the Events menu
5. Check that filter is lost

**Expected Result**
1. Filter should be maintained along the three views of the vulnerability detection module

**Video**

[filter.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/11089305/b15b9663-fb45-4c30-9307-95c2a0be6696)

**Comment by asteriscos** [comment]
Hi @Rebits, 
this behavior works as intended. It works this way, because the _Dashboard_ and _Inventory_ views use the `wazuh-states-vulnerabilities` index-pattern and the _Events_ view uses the `wazuh-alerts-*` index-pattern. Therefore, we must clean the filters which are not a pinned agent or the default cluster name filter.
I will close this.

![Peek 2024-02-16 17-46](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/74b24b9d-5fb9-481e-a3fc-e4797167900f)
