### ISSUE TITLE
Debian agent includes Windows agent syscheck events

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-dashboard-plugins#6655]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | RC1 | Any |

**Description**
Difficult to replicate error appear in the Debian endpoint menu. In the FIM recent events menu some Windows agent events appeared

**Preconditions**
1. Full environment with a Debian and a Windows agent

**Steps to reproduce**
No steps to reproduce can be provided because this issue was impossible to reproduce

**Expected Result**
1. No Windows agent events should be included in Debian agent

**Actual Result**
1. Windows agent events are included in some menus of the Debian agent

> [!NOTE]
> Additional information will be furnished once the issue has been successfully replicated

**Screenshots**

![debian_bad_dashboard](https://github.com/wazuh/wazuh/assets/11089305/a176150e-9755-48af-9a32-6a0374bcf286)

**Comment by asteriscos** [comment]
We were able to successfully replicate the issue in Wazuh 4.7.4 with a Windows agent showing Linux paths. 
This was due to the  **_Sample Data_** generated alerts with Linux data, but matching the ID of a real Windows agent. We strongly believe this is also the case. We won't be adding this validation to the script that generates sample data, therefore I will close this as not planned.

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/58fd4643-5e76-41d1-8c31-1b5eb705f107)
