### ISSUE TITLE
Discover plugin legacy callout warning message

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6683]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.8.0 | 10 | - |

## Description
We found out that the Discover plugin still shows the callout with the legacy warning in certain conditions. 

**Steps to reproduce**
1. Navigate to **Configuration assessment** and select an agent
2. Navigate to the **Discover** plugin
3. See the callout "info" message

**Screenshots**

![image](https://github.com/wazuh/wazuh-dashboard-plugins/assets/9343732/4cbda82b-1f4a-42dd-815f-dc106a95c478)

**Comment by JuanGarriuz** [comment]
### Update 17/05 

The state `discover:deprecation-notice:show` is initially set to false, controlled by this file: `plugins/main/public/plugin.ts`. This prevents the rendering of the component when the application loads or the page is refreshed. However, this file: `plugins/main/public/components/agents/sca/dashboard/dashboard.tsx` performs a clearing of the local storage, causing the message to be displayed.

Due to the lack of context, we are investigating the potential repercussions of removing the local storage clearing.
