### ISSUE TITLE
Quick switch between tabs vulnerabilities gives a filter error

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-dashboard-plugins#6764]
## Description
When changing tabs quickly in vulnerabilities the filters disappear, between dashboard/invetory and events.

## Steps to reproduce
1. Navigate to 'Vulnerability detection'
2. Change tabs quickly

https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/caa9d6ef-cd86-47dd-bac9-17904c554eab

## Tasks

- [ ] Researching the problem

**Comment by yenienserrano** [comment]
From what I could find when switching fast tabs it will first load the filters with the corresponding index pattern well and then load the filters with the vulnerability index pattern and that's why it has no filters. I still can't find out why the other dashboards don't show the filters if they are loaded with the correct index pattern.


https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/ea0128f9-96c5-49be-a7ca-2c19ea153195

**Comment by jbiset** [comment]
## Update 13/06/2024

### Research and solution proposal
The problem is apparently due to the fact that in the initialization of the datasource in the useEffect of the use-data-source hook, despite canceling the subscription in the return of the useEffect, it seems to continue to be active, causing its effect to be produced asynchronously later that the next component is rendered. For now there is a possible solution by checking at different times of the useEffect to avoid this if the component is no longer mounted. As far as it has been tested it seems to solve the problem. However, it is being analyzed if it is the best way to solve it at the code level.

**Comment by jbiset** [comment]
## Update 14/06/2024

The solution proposal is evaluated and improved by adding the `useIsMounted` hook so that it can be reused in similar cases, also taking into account the `AbortController`.
