### ISSUE TITLE
Cannot POST events by using DevTools

### ISSUE THREAD

**Issue by afarguellesd** [wazuh/wazuh-dashboard-plugins#6899]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.8.0 | Wazuh Manager | Manager | Manual installation | Ubuntu |
| v4.8.0 | Wazuh Manager | Manager | Cloud | Cloud |

Trying to use DevTools to POST events by using Wazuh API, I got this result

```json
{
  "error": "3013",
  "message": {
    "title": "Bad Request",
    "detail": "'Event value 1,{\"someKey\": \"Event value 2\"}' is not of type 'array' - 'events'"
  }
}
```

The console input is as follows:

```
# Using sample payload to POST some events

POST /events?pretty=true
{
  "events": [
    "Event value 1",
    "{\"someKey\": \"Event value 2\"}"
  ]
}
```

I enabled debug to `2` on all components. Besides the request in the API log, there is no more information about the errors in the logs.

```plaintext
2024/07/29 12:08:06 INFO: wazuh-wui 127.0.0.1 "POST /events" with parameters {"pretty": "true"} and body {"events": 42} done in 0.023s: 400
```

I'm attaching an image of the DevTools screen
![Wazuh01_DevTools events error](https://github.com/user-attachments/assets/1e155a33-76c1-4642-9ee1-ea4e4486ebd1)

**Comment by Desvelao** [comment]
@QU3B1M asked us about this problem.

I was researching this, and it seems a bug on the Wazuh plugin for Wazuh dashbord. Tested with 4.8.1.
I could replicate it using 4.8.1 and I found the Wazuh plugins are mapping the value for `events` property from an array to a string comma-separated

This piece of code https://github.com/wazuh/wazuh-dashboard-plugins/blob/v4.8.1-2.10.0/plugins/main/server/controllers/wazuh-api.ts#L780-L789 is transforming the `events` array property of API request via Dev Tools into a string comma-separated.

I don't have context about this transformation. This needs a deep analysis of the use cases and decide if the code makes sense for some use cases or we should add another exception to avoid that transformation.

**Comment by Desvelao** [comment]
I was analyzing the Wazuh API requests done by the frontend side and they should not send a parameter that is an array (first level of object), so the condition to transform the array could not be executed for the Wazuh API request done in the business logic of the plugin. So, removing the transformation commented here https://github.com/wazuh/wazuh-dashboard-plugins/issues/6899#issuecomment-2270941914 should not cause problems because the transformation is not used according to the parameter received.

In the case we detected some API requests failing after removing this transformation on the backend side, we should ensure the frontend parameters are defined as expected.

**Comment by Desvelao** [comment]
I created a pull request https://github.com/wazuh/wazuh-dashboard-plugins/pull/6908 with the proposed solution commented here https://github.com/wazuh/wazuh-dashboard-plugins/issues/6899#issuecomment-2288228812
