### ISSUE TITLE
Initial state of the filters reset when reloading the page

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6918]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 05 | - |

## Description
If the user applies a set of filters to change the time interval of a query and then reloads the page the filters are lost.

**Expected Result**
1. The filters should be maintained

**Actual Result**
1. The initial filters reset to default values

**Screenshots**
![Peek 2024-08-19 18-10](https://github.com/user-attachments/assets/9aa09b90-6c7f-4d65-ac10-4ede439d847a)

**Comment by jbiset** [comment]
## Research 2024-08-19

In the `wz-discover` (`plugins/main/public/components/common/wazuh-discover/wz-discover.tsx`) component, during datasource initialization, when the `useDataSource` hook is used, the filters are initialized in `[]`, since no initial filters are passed to it, for example, those in the URL.

```typescript
const {
    dataSource,
    filters,
    fetchFilters,
    fixedFilters,
    isLoading: isDataSourceLoading,
    fetchData,
    setFilters,
  } = useDataSource<tParsedIndexPattern, PatternDataSource>({
    repository: AlertsRepository, // this makes only works with alerts index pattern
    DataSource,
  });
```

This leads to the state being lost when the page is reloaded, since when the component is rendered again it does not maintain the filters of either the OSD FilterManager or the filters based on the URL.
To solve the problem, we are analyzing whether to use some `OSD FilterManager` (`src/plugins/data/public/query/filter_manager/filter_manager.ts`) method to capture the URL filters or use a communication method between renders through `localStorage` to maintain the state of the filters.
