### ISSUE TITLE
Vulnerabilities dashboard resets the filters after reloading the page

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6937]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 06 | Chrome, Firefox, Safari, etc |

**Description**
Vulnerabilities dashboard resets the filters after reloading the page. 

**Steps to reproduce**
1. Go to Vulnerabilities > Dashboard
2. Add a filter (agent.name for example)
3. Reload the browser

**Expected Result**
1. It should keep the filters after reloading the page

**Actual Result**
1. Resets the filters

**Screenshots**

![Peek 2024-08-21 18-41](https://github.com/user-attachments/assets/15584424-6d67-406b-a4dc-9c857c3351e6)

**Comment by Desvelao** [comment]
# Research

The problem is happening in any tab of the modules.

The module tabs are rendered by the `Overview` component. This has an effect to sync the URL with the filterManager. To do this, it creates an `appStateContainer` with an initial state that contains the `appState` filters. Then the `connectToQueryState` https://github.com/wazuh/wazuh-dashboard-plugins/blob/4.9.0/plugins/main/public/components/overview/overview.tsx#L83 is executed and check if the state of `appStateContainer` and `data.query` are compatibles according to the sync configuration. In our case, compare the `appState` filters and they could be differents. This causes the filters on the `appStateContainer` are updated with the filters on the `filterManager` that has no filters.

![image](https://github.com/user-attachments/assets/e5762e32-9458-4954-9545-7a452a423e95)
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.13.0/src/plugins/data/public/query/state_sync/connect_to_query_state.ts#L225-L234

In the effect of the `Overview` component, when this method is called, the filters on the `appStateContainer` are cleaned causing the filters on `_a` query parameter are cleaned.
https://github.com/wazuh/wazuh-dashboard-plugins/blob/4.9.0/plugins/main/public/components/overview/overview.tsx#L73

For `Events` tabs, the filters on the `_a` query parameter are cleaned as explained above, but then the data source sets the filters on the filter manager, and the sync filterManager-URL causes the filters are added again to `_a` query parameter.

**Comment by Desvelao** [comment]
I was in a meeting with @yenienserrano to review the origin of the code to sync the URL-filterManager.

I saw in some plugins that use the `connectToQueryState`, it has some logic to set the `appState` filters: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.13.0/src/plugins/dashboard/public/application/utils/use/use_dashboard_app_state.tsx#L84-L86

This logic is present on Wazuh dashboard plugins 4.8.0 too, so we guess this was not migrated from AngularJS to ReactJS: https://github.com/wazuh/wazuh-dashboard-plugins/blob/v4.8.2-2.10.0/plugins/main/public/kibana-integrations/kibana-discover.js#L248-L252

Adding this fix on the `Overview` component that renders the module tabs is causing problems on the search bars. I am reviewing this.
![image](https://github.com/user-attachments/assets/28ee5351-1478-49de-8402-57226b255f6b)
![image](https://github.com/user-attachments/assets/391b6632-ab2a-47fd-acd2-38c9f850c606)

**Comment by Desvelao** [comment]
# Update

I could fix the problem related to the search bar. Syncing the query parameter is causing indirectly the query used on the Dashboard was not set and the query search bar did not display the component.

I created a pull request https://github.com/wazuh/wazuh-dashboard-plugins/pull/6944.

**Comment by Desvelao** [comment]
The issue was moved to 4.9.0 so it needed to open a new pull request that contains the changes.

Pull request: https://github.com/wazuh/wazuh-dashboard-plugins/pull/6950
