### ISSUE TITLE
User interface toggle for vulnerability evaluation status

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh-dashboard-plugins#6957]
## Description

There are some vulnerabilities that have not been evaluated yet, therefore some fields are missing.
This issue aims to implement a toggle in the user interface to display the dispute/evaluation status using the `wazuh.vulnerability.under_evaluation` filter.

Vulnerabilities still under evaluation:
![image](https://github.com/user-attachments/assets/762dac00-0662-46e6-bd11-a07c569a0814)

## Tasks
- [ ] Create a filter control that allows the user to filter `wazuh.vulnerability.under_evaluation` by `true` or `false`
  - This could be done by:
    - developing a new action button like the `Explore agent` selector 
![image](https://github.com/user-attachments/assets/36242fa5-7b64-4e9a-be8b-bc8cf231e730)

    - or perhaps a new type of control in the "implicit filters" section of the search bar.
![image](https://github.com/user-attachments/assets/d63e48bc-6111-4f44-b79e-eb3303463bfc)

- [x] Adapt Wazuh dashboard sample data to consider this case, so it can be easily tested.

### Vulnerabilities dashboard
![image](https://github.com/user-attachments/assets/c6eb4e1f-9e67-4eaf-9205-32ed5215a0e8)

### Vulnerabilities inventory
![image](https://github.com/user-attachments/assets/caabcc22-06df-48f6-b072-a381aa1c2261)

**Comment by Desvelao** [comment]
# Proposition 1

This defines a form control in the same row of the search bar filters at the end with the ability to select an option to filter:
- `unset`: no filter. This is the initial value.
- `yes`: add a filter `wazuh.vulnerability.under_evaluation: false`
- `no`: add a filter `wazuh.vulnerability.under_evaluation: true`

Clicking on the `yes` or `no` option adds a user filter to the search bar too. This causes the data related to the filter is displayed in two places. This approach is similar to the `GitHub/Office 365 > Panel` views when using the simple search bar.

![image](https://github.com/user-attachments/assets/6cf94e6b-98be-4222-aea1-4e23dcd91ddd)
![image](https://github.com/user-attachments/assets/5712a0b2-cda5-4d3b-a650-d4376528ae33)
![image](https://github.com/user-attachments/assets/36edd47d-8638-4882-b68e-e2567f7590c4)

**Comment by Desvelao** [comment]
# Proposition 2

Add an editable filter neat to the fixed filters. This approach reduces the occuped space from the [propostion#1](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6957#issuecomment-2326464542).

This needs changes in the data source to support this type of editable filters. Depending on the case, this filter could not be shared because this could not be present in the URL.

![image](https://github.com/user-attachments/assets/7f23707e-ce07-4236-abaf-9aaea8585753)
![image](https://github.com/user-attachments/assets/68d748ca-b3ee-4938-abf5-ca3090dc1641)
![image](https://github.com/user-attachments/assets/4b8ddbfb-35c7-44c0-bcf8-96fedd7e15ee)

> This is a POC, and the badge should have similar height of other filters.

**Comment by Desvelao** [comment]
# Proposition 4

Add a form control near to the fixed filters. This form control adds user filters with a `controlledBy` property to identify. The user filters should not include the filter.

The render could be similar to [Proposition 2](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6957#issuecomment-2326478515).

![Image](https://github.com/user-attachments/assets/faced425-1002-4cf3-988d-775f3a5d234a)
> This is a POC, the UI could need some enhancements.

If the controlled filter is rendered by the user search bar filters, when using the `Disable all` option the filter is kept on the URL meanwhile, if the controlled filter is not passed to the user search bar filter, using the `Disable all` option, the filter dissappear from the URL. The result is the same, the filter should be used, but it could have other unknown consequences.

**Comment by Desvelao** [comment]
I created the visualization using the `Visualize` application

- type: metric
- aggregation: `Filters`
  - Filter1: `wazuh.vulnerability.under_evaluation:false`
    Label: `Evaluated`
  - Filter2: `wazuh.vulnerability.under_evaluation:true`
    Label: `Pending`

and I add it into the dashboard porting the visualization definition to the definition on the plugin.

Result:
![Image](https://github.com/user-attachments/assets/e5a9b989-287e-4e1b-82bf-334af98de055)

Notes:
- `Count` label of aggregation was replaced by `Evaluation` because the dashboard where the visualization is added, has other indicators that use `Severity` count label.
