### ISSUE TITLE
Events table must order the selected columns first

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#6978]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.9.0 | 07 | Chrome, Firefox, Safari, etc |

# Description

The events table shows a list of all the available fields in the index pattern to select columns for the table. These fields must order first the already selected columns and then list thee rest of the available fields.

**Expected Result**
1. Show first the selected columns
2. List the rest of the available fields

**Screenshots**

![image](https://github.com/user-attachments/assets/54750aed-0896-46cb-a3d1-0d78683ad128)

**Comment by JuanGarriuz** [comment]
### Research

When columns are added, the table does not function as expected because they are added and sorted according to ASCII, causing the rest of the columns (at least the first time) to be reordered incorrectly when a new column is added.

It is expected that when a table is added, the default columns are shown first, followed by the rest of the columns

![image](https://github.com/user-attachments/assets/85a280d8-5efd-464c-a6bb-b1b0dc6aafbb)
