### ISSUE TITLE
Server-side logger is unable to parse some errors

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard-plugins#7165]
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.10.0 | 04 | Chrome, Firefox, Safari, etc |

# Description

Since we are using the native OpenSearch logger to log server-side errors, there are some data structures that cannot be parsed and a generic exception is thrown.
We need to check all the log calls that implement `context.wazuh.logger` and make sure it receives a string or a Error object type.

**Steps to reproduce**
1. Navigate to Endpoints summary
2. Search for `| ; ! # $ ^ & * ( )` in the table
3. See the unhandled error

**Expected Result**

![image](https://github.com/user-attachments/assets/8bd22727-6915-4e0e-bc36-b27613d0bc9b)

**Actual Result**

![image](https://github.com/user-attachments/assets/196c1712-84ee-458e-b77c-45ed53b85c6e)

**Additional context**

The logger is unable to parse this data structure.

https://github.com/wazuh/wazuh-dashboard-plugins/blob/v4.10.0-alpha3/plugins/main/server/controllers/wazuh-api.ts#L639-L640

**Comment by Machi3mfl** [comment]
##

## Wazuh api.ts 



- [makeRequest](https://github.com/wazuh/wazuh-dashboard-plugins/blob/7cf25b01f9380e0a0bb9f4b199d23df5b420edc8/plugins/main/server/controllers/wazuh-api.ts#L471-L657) method is responsive to make all the requests to the Wazuh API. When the API returns an error has the following structure:

```
{
  "title": "Unauthorized",
  "detail": "No authorization token provided"
}
``` 

To prevent that the logger receive an unexpected object or data we must to check if the response is an error using the isAxiosError property, because the makerequest method use axios to make the HTTP requests.



[API Docs](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_agent_outdated)
